spring.application.name=personal-shopper-app
server.port=8080
spring.datasource.url=jdbc:sqlite:data/personal_shopper_java.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.thymeleaf.cache=false
app.excel-path=../TABLA_PERSONAL_SHOPPER_COMPLETA.xlsx
